version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: 'Install dependencies'
          command: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'Build'
          command: npm run build
      - run:
          name: 'Check style'
          command: npm run check
      - run:
          name: 'Test'
          command: npm run test
